table DimProductSubcategory
	lineageTag: e190caae-b32e-4e2e-8947-cc6181e415a6

	column ProductSubcategoryKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 5b5c5381-3bc0-442e-b33c-579c58c35acf
		summarizeBy: none
		sourceColumn: ProductSubcategoryKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ProductSubcategoryName
		dataType: string
		lineageTag: 2ac20e61-4ce0-419a-a9d4-85b72ec0763c
		summarizeBy: none
		sourceColumn: ProductSubcategoryName

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ProductCategoryKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: e241b6b8-9f81-445f-ba4e-c92bb4968d7c
		summarizeBy: none
		sourceColumn: ProductCategoryKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition DimProductSubcategory = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Badr\Courses\Power BI\Projects\Contoso-Sales-Analytics\resources\ContosoData\DimProductSubcategory.csv"),[Delimiter=",", Columns=3, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ProductSubcategoryKey", Int64.Type}, {"ProductSubcategoryName", type text}, {"ProductCategoryKey", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

