table DimProductCategory
	lineageTag: b76821d3-1ac8-4c02-a053-59bc0cacfbb7

	column ProductCategoryKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 939a7739-1b82-40b9-8dda-cf095812462f
		summarizeBy: none
		sourceColumn: ProductCategoryKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ProductCategoryName
		dataType: string
		lineageTag: 82e8e23e-1354-4a21-bc10-3c38b6baf7bb
		summarizeBy: none
		sourceColumn: ProductCategoryName

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition DimProductCategory = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Badr\Courses\Power BI\Projects\Contoso-Sales-Analytics\resources\ContosoData\DimProductCategory.csv"),[Delimiter=",", Columns=2, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ProductCategoryKey", Int64.Type}, {"ProductCategoryName", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

